"""add room fields

Revision ID: 07f2372d6219
Revises: 966e76f30ab7
Create Date: 2020-09-01 18:29:19.375754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f2372d6219'
down_revision = '966e76f30ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('building_code', sa.String(), nullable=True))
    op.add_column('students', sa.Column('entryway', sa.String(), nullable=True))
    op.add_column('students', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('suite', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'suite')
    op.drop_column('students', 'floor')
    op.drop_column('students', 'entryway')
    op.drop_column('students', 'building_code')
    # ### end Alembic commands ###
