"""add leave

Revision ID: 82852cb18d9b
Revises: ffc7415383f2
Create Date: 2020-09-15 22:25:55.788522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82852cb18d9b'
down_revision = 'ffc7415383f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('leave', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'leave')
    # ### end Alembic commands ###
