"""add registered_on

Revision ID: ffc7415383f2
Revises: 1cfed6c65ec0
Create Date: 2020-09-05 18:02:18.503210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc7415383f2'
down_revision = '1cfed6c65ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###
